=== aminfa/SEDE/testrsc/json-schema/requests/RunRequest.schema.json
{
    "$id": "https://github.com/fmohr/SEDE/tree/master/SEDE.core/src/main/resources/json-schema/requests/RunRequest.schema.json",
    "type": "object",
    "definitions": {},
    "$schema": "http://json-schema.org/draft-06/schema#",
    "properties": {
        "composition": {
            "$ref": "SequentialComposition.schema.json"
        },
        "requestId": {
            "type": "string",
            "examples": [
                "exec-id-0"
            ]
        },
        "inputs": {
            "type": "object"
        },
        "policy": {
            "$ref": "ResolvePolicy.schema.json"
        }
    }
}

=== aminfa/SEDE/SEDE.plugins/http_/src/test/resources/run-requests/run2.json
{
    "composition": [
        "g1 = demo.math.Gerade::__construct({b, 1})",
        "g2 = demo.math.Gerade::__construct({a, -1})",
        "a1 = demo.math.Addierer::__construct({5})",
        "n1 = g1::nullstelle()",
        "n2 = g2::nullstelle()",
        "l2 = a1::summierListe({n1, n2})",
        "l3 = a1::addierListe({l2})",
        "l4 = a1::summierListe({l3, l2})",
        "g1::liagtAufGerade({l4})",
        "b1 = g2::liagtAufGerade({l4})"
    ],
    "requestId": "run2",
    "inputs": {
        "a": {
            "data": 1,
            "type": "Number"
        },
        "b": {
            "data": -1,
            "type": "Number"
        }
    },
    "policy": {
        "service-policy": "ALL",
        "return-policy": "ALL"
    }
}
