=== aminfa/SEDE/SEDE.core/base/src/main/resources/json-schema/requests/ResolveRequest.schema.json
{
  "$id": "https://github.com/fmohr/SEDE/tree/master/SEDE.core/src/main/resources/json-schema/requests/ResolveRequests.schema.json",
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "properties": {
    "composition": {
      "$ref" : "SequentialComposition.schema.json"
    },
    "requestId": {
      "type": "string",
      "examples": [
        "exec-id-0"
      ]
    },
    "input-fields": {
      "type": "object",
      "properties": {
        "service-instance-map": {
          "type": "object"
        },
        "field-types": {
          "type": "object"
        }
      }
    },
    "client-executor": {
      "$ref" : "ExecutorRegistration.schema.json"
    },
    "policy": {
      "$ref" : "ResolvePolicy.schema.json"
    }
  }
}

=== aminfa/SEDE/testrsc/resolve-requests/ResolveRequest_03.json
{
    "client-executor": {
        "contact-info": { "id": "client executor" }
    },
    "composition": [
        "a = demo.math.Addierer::__construct({1})",
        "n = a::addier({in3})",
        "p1 = s1::calc({n})",
        "b1 = s1::liagtAufGerade({p1})",
        "a = demo.math.Addierer::__construct({n})",
        "n = a::addier({in4})",
        "p2 = s2::achsenabschnitt()",
        "p1 = a::summierListe({p1, p2})",
        "a = demo.math.Addierer::__construct({n})",
        "p2 = s2::nullstelle()",
        "p1 = a::summierListe({p1, p2})",
        "p2 = s1::achsenabschnitt()",
        "p1 = a::summierListe({p1, p2})",
        "n = a::summier({p1})",
        "a = demo.math.Addierer::__construct({n})",
        "p2 = s1::nullstelle()",
        "p1 = a::summierListe({p1, p2})",
        "bool2 = s2::liagtAufGerade({p2})"
    ],

    "requestId": "id",

    "input-fields": {
        "service-instance-map": {
            "s1": {
                "classpath": "demo.math.Gerade",
                "host": "exec_2",
                "id": "id0"
            },
            "s2": {
                "classpath": "demo.math.Gerade",
                "host": "exec_2",
                "id": "id1"
            }
        },
        "field-types": {
            "in1": "Array",
            "in2": "Array",
            "in3": "Number",
            "in4": "Number",
            "s1": "ServiceInstanceHandle",
            "s2": "ServiceInstanceHandle"
        }
    },
    "policy": {
        "service-policy": [],
        "return-policy": ["p1"]
    }
}

=== aminfa/SEDE/SEDE.plugins/http_/src/test/resources/resolve-requests/ResolveRequest_01.json
{
    "client-executor": {
        "contact-info": {
            "id": "client executor"
        }
    },
    "composition": [
        "a=demo.math.Addierer::__construct({100})",
        "d=a::addier({20})",
        "f=a::addierListe({b})",
        "d=e::liagtAufGerade({f})"
    ],
    "requestId": "id",
    "input-fields": {
        "service-instance-map": {
            "e": {
                "classpath": "demo.math.Gerade",
                "executorId": "exec_2",
                "id": "id0"
            }
        },
        "field-types": {
            "b": "Arr",
            "c": "Arr",
            "e": "ServiceInstanceHandle"
        }
    },
    "policy": {
        "service-policy": "ALL",
        "return-policy": "ALL"
    }
}

=== aminfa/SEDE/testrsc/resolve-requests/ResolveRequest_02.json
{
    "client-executor": {
        "contact-info": { "id": "client executor" }
    },
    "composition": [
        "adder1 = demo.math.Addierer::__construct({100})",
        "n1 = adder1::addier({in3})",
        "p1 = s1::calc({n1})",
        "bool1 = s1::liagtAufGerade({p1})",
        "adder1 = demo.math.Addierer::__construct({10})",
        "n2 = adder1::addier({in4})",
        "p2 = s2::calc({n2})",
        "bool2 = s2::liagtAufGerade({p2})"
    ],

    "requestId": "id",

    "input-fields": {
        "service-instance-map": {
            "s1": {
                "classpath": "demo.math.Gerade",
                "executorId": "exec_2",
                "id": "id0"
            },
            "s2": {
                "classpath": "demo.math.Gerade",
                "executorId": "exec_2",
                "id": "id1"
            }
        },
        "field-types": {
            "in1": "Array",
            "in2": "Array",
            "in3": "Number",
            "in4": "Number",
            "s1": "ServiceInstanceHandle",
            "s2": "ServiceInstanceHandle"
        }
    },
    "policy": {
        "service-policy": ["s1", "s2"],
        "return-policy": ["bool1", "s2"]
    }
}
